# Generated by Django 5.2.7 on 2025-10-28 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('vm', 'Virtual Machine'), ('storage', 'Storage Bucket'), ('database', 'Database')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('memory_gb', models.IntegerField(default=2)),
                ('storage_gb', models.IntegerField(default=20)),
                ('cost_per_hour', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoScalingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(default='cpu_usage', max_length=50)),
                ('threshold', models.FloatField()),
                ('action', models.CharField(choices=[('scale_up', 'Scale Up'), ('scale_down', 'Scale Down')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_rules', to='resources.resource')),
            ],
        ),
    ]
